sudo: required
services:
    - docker

before_install:
    - docker build -t eman32387/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true eman32387/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-827161207058"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
language: generic